version: "3"

services:
  python_app_main:
    image: test
    command:
      [
          "gunicorn", "-w 2", "-k uvicorn.workers.UvicornWorker",
          "app.main:app",
          "--bind", "0.0.0.0:8000"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    ports:
      - 8000:8000
  python_task:
    image: test
    command:
      [
#        "cd llm/tasks", "&&", "celery -A chatwiztasks worker -Q chatwiztasks_queue --loglevel=INFO --hostname=chatwiz --autoscale=2,1"
#        "cd llm && ls"
        "celery", "-A", "llm.tasks.chatwiztasks", "worker", "-Q", "chatwiztasks_queue", "--loglevel=INFO", "--hostname=chatwiz", "--autoscale=2,1"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 80:80
#    volumes:
#      - nginx_volume:/etc/nginx/conf.d/default.conf
    depends_on:
      - python_app_main
#  celery:
#    image: celery
#    command: celery -A app.worker worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.12.4
    ports:
      - 5672:5672
volumes:
  nginx_volume: