version: "3"

services:

  python_fastapi:
    image: chatwizapi
    command:
      [
          "gunicorn", "-c",  "gunicorn_config.py",  "app.main:app"
      ]

    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    ports:
      - 8000:8000

  celery_worker:
    image: chatwizapi
    command:
      [
          "celery", "-A", "app.llm.tasks.chatwiztasks", "worker", "-Q", "chatwiztasks_queue",
          "--loglevel=DEBUG", "--hostname=chatwiz", "--autoscale=2,1"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    depends_on:
      - rabbitmq

  chatwizapi_nginx:
    image: chatwiz_nginx
    ports:
      - 80:80
#    volumes:
#      - nginx_volume:/etc/nginx/conf.d/default.conf
    depends_on:
      - python_fastapi

  rabbitmq:
    image: rabbitmq:3.12.4
    ports:
      - 5672:5672

volumes:
  nginx_volume: