version: "3"

services:

  python_fastapi:
    image: chatwizapi
    command:
      [
          "gunicorn", "-w 2", "-k uvicorn.workers.UvicornWorker",
          "app.main:app",
          "--bind", "0.0.0.0:8000"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    ports:
      - 8000:8000

  celery_worker:
    image: chatwizapi
    command:
      [
        "celery", "-A", "llm.tasks.chatwiztasks", "worker", "-Q", "chatwiztasks_queue", "--loglevel=INFO", "--hostname=chatwiz", "--autoscale=2,1"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    depends_on:
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 80:80
#    volumes:
#      - nginx_volume:/etc/nginx/conf.d/default.conf
    depends_on:
      - python_fastapi
    
  rabbitmq:
    image: rabbitmq:3.12.4
    ports:
      - 5672:5672
      
volumes:
  nginx_volume: