version: "3"

services:

  python_fastapi:
    image: chatwiz_api
    command:
      [
          "gunicorn", "-w", "2", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    ports:
      - 8000:8000

  celery_worker:
    image: chatwiz_api
    command:
      [
          "celery", "-A", "app.llm.tasks.chatwiztasks", "worker", "-Q", "chatwiztasks_queue",
          "--loglevel=DEBUG", "--hostname=chatwiz", "--autoscale=2,1"
      ]
    environment:
      APP_BROKER_URI: "amqp://rabbitmq"
    depends_on:
      - rabbitmq

  chatwizapi_nginx:
    image: chatwiz_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - python_fastapi

  rabbitmq:
    image: rabbitmq:3.12.4
    ports:
      - 5672:5672

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "11111111"
      POSTGRES_EXTENSIONS: vector
    ports:
      - "${POSTGRES_PORT}:5432"