[tool.black]
line-length = 120
target-version = ['py36']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | venv
)/

'''

[tool.isort]
profile = "black"
skip = [".gitignore", ".dockerignore", "venv"]

